### ISSUE TITLE
TokenError

### ISSUE THREAD

**Issue by midora41** [nicholastay/passport-discord#10]
``    at Strategy.OAuth2Strategy.parseErrorResponse (D:\1master\NDB\node_modules\passport-oauth2\lib\strategy.js:329:12)
    at Strategy.OAuth2Strategy._createOAuthError (D:\1master\NDB\node_modules\passport-oauth2\lib\strategy.js:376:16)
    at D:\1master\NDB\node_modules\passport-oauth2\lib\strategy.js:166:45
    at D:\1master\NDB\node_modules\oauth\lib\oauth2.js:191:18
    at passBackControl (D:\1master\NDB\node_modules\oauth\lib\oauth2.js:132:9)
    at IncomingMessage.<anonymous> (D:\1master\NDB\node_modules\oauth\lib\oauth2.js:157:7)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1055:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)``

**Comment by midora41** [comment]
sorry about that was a problem in my code Fixed now

**Comment by PassTheMayo** [comment]
@midora41 May I ask how you fixed it?

**Comment by TotomInc** [comment]
@midora41 how did you fixed it?

**Comment by anselal** [comment]
@midora41 how did you fix this ?
