### ISSUE TITLE
TokenError

### ISSUE THREAD

**Issue by TheMrSpike** [nicholastay/passport-discord#17]
Whenever I go to /api/login/discord, it works normally and redirects me to the discord link. Once authorized, I get redirected to /api/discord/callback but with a TokenError.

`TokenError
    at Strategy.OAuth2Strategy.parseErrorResponse ([Working Directory]\node_modules\passport-oauth2\lib\strategy.js:358:12)
    at Strategy.OAuth2Strategy._createOAuthError ([Working Directory]\node_modules\passport-oauth2\lib\strategy.js:405:16)
    at [Working Directory]\node_modules\passport-oauth2\lib\strategy.js:175:45
    at [Working Directory]\node_modules\oauth\lib\oauth2.js:191:18
    at passBackControl ([Working Directory]\node_modules\oauth\lib\oauth2.js:132:9)
    at IncomingMessage.<anonymous> ([Working Directory]\node_modules\oauth\lib\oauth2.js:157:7)
    at IncomingMessage.emit (events.js:202:15)
    at endReadableNT (_stream_readable.js:1129:12)
    at processTicksAndRejections (internal/process/next_tick.js:76:17)`

`const express = require("express");
const session = require("express-session");
const passport = require("passport");
const Strategy = require("passport-discord").Strategy
const logger = require("./Logger.js");

const PORT = process.env.PORT || 8080;
const URL =
  process.env.NODE_ENV === "production"
    ? `http://localhost:${PORT}` // this is the production version
    : `http://localhost:${PORT}`;

const CLIENT_ID = process.env.CLIENT_ID;
const CLIENT_SECRET = process.env.CLIENT_SECRET;
const WEB_SECRET = process.env.WEB_SECRET;

const app = express();

const redirect = `${URL}/api/discord/callback`

//                                               OAUTH2 BEGINS
var scopes = ["identify"];

passport.serializeUser(function(user, done) {
    done(null, user);
});
  passport.deserializeUser(function(obj, done) {
    done(null, obj);
});

passport.use(new Strategy({
    clientID: CLIENT_ID,
    clientSecret: CLIENT_SECRET,
    callbackURL: redirect,
    scope: scopes
}, function(accessToken, refreshToken, profile, done) {
    process.nextTick(function() {
        return done(null, profile);
    });
}));

app.use(session({
    secret: WEB_SECRET,
    resave: false,
    saveUninitialized: false
}));

function checkAuth(req, res, next) {
    if (req.isAuthenticated()) return next();
    res.send('not logged in :(');
}

app.use(passport.initialize());
app.use(passport.session());

function checkAuth(req, res, next) {
    if (req.isAuthenticated()) return next();
    res.send('not logged in :(');
}

app.get('/api/discord/login', passport.authenticate('discord', { scope: scopes }), function(req, res) {});
app.get('/api/discord/callback',
    passport.authenticate('discord', { failureRedirect: '/api/discord/login' }), function(req, res) { res.redirect('/info') } // auth success
);
app.get('/api/discordlogout', function(req, res) {
    req.logout();
    res.redirect('/api/discord/login');
});
app.get('/info', checkAuth, function(req, res) {
    //console.log(req.user)
    res.json(req.user);
});

//                                               OAUTH2 ENDS`

**Comment by reetou** [comment]
Same.

**Comment by TheMrSpike** [comment]
Last update was a year ago, this probably broke due to updates. I might make a replacement module tbh.

**Comment by PLASMAchicken** [comment]
This still works fine for me are you sure you set the `clientSecret: CLIENT_SECRET,`?

**Comment by ZE0TRON** [comment]
Same here.

**Comment by hydraindia** [comment]
> After digging the source code I have found out that if you some parameters wrong to the strategy it gives you this error. Also the callback url should be a global url like https://example.com/discord/auth/ not like /discord/auth.

Yeah, I faced the same issue if you enter any wrong parameter to the strategy it will fail.

**Comment by ljosberinn** [comment]
> Also the callback url should be a global url like https://example.com/discord/auth/ not like /discord/auth.
Cannot confirm, works fine without a global url.
However, can confirm that if you encounter this error, double check your token/secret and that they are properly set.

**Comment by huss-a** [comment]
Please make sure to double check your Client ID && Secret, because I didn't pay attention to them and spent an hour trying to debug a problem that was occuring because my secret was missing a hiphon 😐. Pain.

**Comment by FHGDev** [comment]
Even after checking all of the parameters to the Strategy it still does this for me.

**Comment by PLASMAchicken** [comment]
User Error
Stop Necro

**Comment by Randomx24** [comment]
`TokenError
    at Strategy.OAuth2Strategy.parseErrorResponse (/home/runner/botlistw-1/node_modules/passport-discord/node_modules/passport-oauth2/lib/strategy.js:358:12)
    at Strategy.OAuth2Strategy._createOAuthError (/home/runner/botlistw-1/node_modules/passport-discord/node_modules/passport-oauth2/lib/strategy.js:405:16)
    at /home/runner/botlistw-1/node_modules/passport-discord/node_modules/passport-oauth2/lib/strategy.js:175:45
    at /home/runner/botlistw-1/node_modules/passport-discord/node_modules/oauth/lib/oauth2.js:191:18
    at passBackControl (/home/runner/botlistw-1/node_modules/passport-discord/node_modules/oauth/lib/oauth2.js:132:9)
    at IncomingMessage.<anonymous> (/home/runner/botlistw-1/node_modules/passport-discord/node_modules/oauth/lib/oauth2.js:157:7)
    at IncomingMessage.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1241:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)`

**Comment by PLASMAchicken** [comment]
Can you post a short & reproduceable code sample ( like on Stackoverflow )

**Comment by mrsaifullah52** [comment]
> After digging the source code I have found out that if you some parameters wrong to the strategy it gives you this error. Also the callback url should be a global url like https://example.com/discord/auth/ not like /discord/auth.



When I'm using the callback URL like this:

`router.get(
	"/redirect",
	passport.authenticate("discord", { failureRedirect: "/" }),
	function (req, res) {
		res.redirect("/info");
	} // auth success
);`

only then the error trigger, so is it safe to redirect the user without passport middleware?

**Comment by prbhanu** [comment]
> > After digging the source code I have found out that if you some parameters wrong to the strategy it gives you this error. Also the callback url should be a global url like https://example.com/discord/auth/ not like /discord/auth.
> 
> Yeah, I faced the same issue if you enter any wrong parameter to the strategy it will fail.
i still get the error

**Comment by benji4411** [comment]
I got this error, it was because i was using public key instead of client secret. I'm pretty dumb i know, but i' sharing in case anyone is as dumb as me.

**Comment by ManrajSaini** [comment]
> I got this error, it was because i was using public key instead of client secret. I'm pretty dumb i know, but i'm sharing in case anyone is as dumb as me.

Thanks benji4411, i also did the same think 😂, it worked now.
