### ISSUE TITLE
InternalOAuthError: Failed to obtain access token

### ISSUE THREAD

**Issue by ItsMrReals** [nicholastay/passport-discord#35]
Now getting this error, friends had to change oauth so it works, but I'm not sure what to do: 

## Error
```
InternalOAuthError: Failed to obtain access token
    at Strategy.OAuth2Strategy._createOAuthError (/home/runner/markplek/node_modules/passport-oauth2/lib/strategy.js:408:17)
    at /home/runner/markplek/node_modules/passport-oauth2/lib/strategy.js:175:45
    at /home/runner/markplek/node_modules/oauth/lib/oauth2.js:191:18
    at passBackControl (/home/runner/markplek/node_modules/oauth/lib/oauth2.js:132:9)
    at IncomingMessage.<anonymous> (/home/runner/markplek/node_modules/oauth/lib/oauth2.js:157:7)
    at IncomingMessage.emit (events.js:326:22)
    at IncomingMessage.EventEmitter.emit (domain.js:483:12)
    at endReadableNT (_stream_readable.js:1241:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

**Comment by tonestrike** [comment]
@ItsMrReals can you share your implementation?

Also, I fixed some bugs in a fork you can use [here](https://github.com/tonestrike/passport-discord). This package isn't being maintained any longer.

**Comment by ItsMrReals** [comment]
> @ItsMrReals can you share your implementation?
> 
> Also, I fixed some bugs in a fork you can use [here](https://github.com/tonestrike/passport-discord). This package isn't being maintained any longer.

Looks like this was a discord issue, it is fixed now.
