### ISSUE TITLE
ReferenceError: err is not defined

### ISSUE THREAD

**Issue by Nas-au** [nicholastay/passport-discord#8]
ReferenceError: err is not defined
    at Strategy._verify (/Users/nas/Desktop/bot_web/index.js:25:5)
    at /Users/../Desktop/bot_web/node_modules/passport-oauth2/lib/strategy.js:193:24
    at /Users/../Desktop/bot_web/node_modules/passport-discord/lib/strategy.js:87:24
    at /Users/../Desktop/bot_web/node_modules/passport-discord/lib/strategy.js:103:13
    at passBackControl (/Users/../Desktop/bot_web/node_modules/oauth/lib/oauth2.js:134:9)
    at IncomingMessage.<anonymous> (/Users/../Desktop/bot_web/node_modules/oauth/lib/oauth2.js:157:7)
    at IncomingMessage.emit (events.js:165:20)
    at endReadableNT (_stream_readable.js:1101:12)
    at process._tickCallback (internal/process/next_tick.js:152:19)

**Comment by HexM7** [comment]
Kindly provide the relevant snippet/code.
